# Общие экспорты схем из всех модулей
from __future__ import annotations

from .auth import Token
from .base import Blank, DeleteResponse, FindBase, FindDateRange, FindResult, PaginatedResponse
from .defense import (
    DefenseDayCreate,
    DefenseDayFull,
    DefenseDayListItem,
    DefenseDayListResponse,
    DefenseRegistrationCreate,
    DefenseRegistrationFull,
    DefenseSlotBase,
    DefenseSlotCreate,
    DefenseSlotFull,
    DefenseSlotListItem,
    DefenseSlotListResponse,
    MyDefenseItem,
    MyDefenseListResponse,
    ProjectTypeCreate,
    ProjectTypeFull,
    ProjectTypeInfo,
    ProjectTypeListResponse,
    ScheduledDefenseItem,
    ScheduledDefenseListResponse,
)
from .project import ProjectCreate, ProjectFull, ProjectListItem, ProjectListResponse, ProjectResponse, ProjectUpdate
from .resume import ResumeCreate, ResumeFull, ResumeListResponse, ResumeResponse, ResumeUpdate
from .user import UserBase, UserCreate, UserFull, UserListItem, UserListResponse, UserResponse, UserUpdate

__all__ = [
    "Blank",
    "DefenseDayCreate",
    "DefenseDayFull",
    "DefenseDayListItem",
    "DefenseDayListResponse",
    "DefenseRegistrationCreate",
    "DefenseRegistrationFull",
    "DefenseSlotBase",
    "DefenseSlotCreate",
    "DefenseSlotFull",
    "DefenseSlotListItem",
    "DefenseSlotListResponse",
    "DeleteResponse",
    "FindBase",
    "FindDateRange",
    "FindResult",
    "MyDefenseItem",
    "MyDefenseListResponse",
    "PaginatedResponse",
    "ProjectCreate",
    "ProjectFull",
    "ProjectListItem",
    "ProjectListResponse",
    "ProjectResponse",
    "ProjectTypeCreate",
    "ProjectTypeFull",
    "ProjectTypeInfo",
    "ProjectTypeListResponse",
    "ProjectUpdate",
    "ResumeCreate",
    "ResumeFull",
    "ResumeListResponse",
    "ResumeResponse",
    "ResumeUpdate",
    "ScheduledDefenseItem",
    "ScheduledDefenseListResponse",
    "Token",
    "UserBase",
    "UserCreate",
    "UserFull",
    "UserListItem",
    "UserListResponse",
    "UserResponse",
    "UserUpdate",
]
